"""user status

Revision ID: 5a491502deb7
Revises: bc6ee0b84ac5
Create Date: 2025-02-26 20:29:04.507017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a491502deb7'
down_revision: Union[str, None] = 'bc6ee0b84ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homeworks', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_tasks_author', 'tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_tasks_author', 'tasks', 'users', ['author_id'], ['id'])
    op.alter_column('homeworks', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
